# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'budgetGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftChart', '~> 1.0'
  pod 'SwiftProtobuf', '~> 1.0'

  # Pods for budgetGame

  target 'budgetGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'budgetGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
